// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchool.WebAPI.Data;

namespace SmartSchool.WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Marta",
                            Sobrenome = "Kent",
                            Telefone = "33225555"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Paula",
                            Sobrenome = "Isabela",
                            Telefone = "3354288"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Laura",
                            Sobrenome = "Antonia",
                            Telefone = "55668899"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Luiza",
                            Sobrenome = "Maria",
                            Telefone = "6565659"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Lucas",
                            Sobrenome = "Machado",
                            Telefone = "565685415"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Pedro",
                            Sobrenome = "Alvares",
                            Telefone = "456454545"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Paulo",
                            Sobrenome = "José",
                            Telefone = "9874512"
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.AlunoDisciplina", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisciplinaID")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlunoId", "DisciplinaID");

                    b.HasIndex("DisciplinaID");

                    b.ToTable("AlunoDisciplinas");

                    b.HasData(
                        new
                        {
                            AlunoId = 1,
                            DisciplinaID = 2
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaID = 4
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaID = 5
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaID = 1
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaID = 2
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaID = 5
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaID = 1
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaID = 2
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaID = 3
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaID = 1
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaID = 4
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaID = 5
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaID = 4
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaID = 5
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaID = 1
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaID = 2
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaID = 3
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaID = 4
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaID = 1
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaID = 2
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaID = 3
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaID = 4
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaID = 5
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Disciplina", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Disciplinas");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Nome = "Matemática",
                            ProfessorId = 1
                        },
                        new
                        {
                            id = 2,
                            Nome = "Física",
                            ProfessorId = 2
                        },
                        new
                        {
                            id = 3,
                            Nome = "Português",
                            ProfessorId = 3
                        },
                        new
                        {
                            id = 4,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            id = 5,
                            Nome = "Programação",
                            ProfessorId = 5
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Lauro"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Roberto"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Ronaldo"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Rodrigo"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Alexandre"
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.AlunoDisciplina", b =>
                {
                    b.HasOne("SmartSchool.WebAPI.Models.Aluno", "Aluno")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.WebAPI.Models.Disciplina", "Disciplina")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("DisciplinaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Disciplina", b =>
                {
                    b.HasOne("SmartSchool.WebAPI.Models.Professor", "Professor")
                        .WithMany("Disciplinas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
